ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';

DROP DATABASE IF EXISTS QLHS;
CREATE DATABASE QLHS;

USE QLHS;

CREATE TABLE IF NOT EXISTS GIAOVIEN
(
	ID VARCHAR(10),
	HOTEN NVARCHAR(50) NOT NULL,
    GIOITINH NVARCHAR(5),
    NGAYSINH DATE,
    DIACHI NVARCHAR(200),
    EMAIL VARCHAR(50),
    
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS NHANVIEN
(
	ID VARCHAR(10),
	HOTEN NVARCHAR(50) NOT NULL,
    GIOITINH NVARCHAR(5),
    NGAYSINH DATE,
    DIACHI NVARCHAR(200),
    EMAIL VARCHAR(50),
    
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS TAIKHOAN
(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TENDN NVARCHAR(50) UNIQUE,
	MATKHAU VARCHAR(20) NOT NULL,
    ISADMIN BOOLEAN DEFAULT(FALSE) NOT NULL,
    NGUOIDUNG VARCHAR(10),
    
	FOREIGN KEY(NGUOIDUNG) REFERENCES GIAOVIEN(ID),
    FOREIGN KEY(NGUOIDUNG) REFERENCES NHANVIEN(ID)
);

CREATE TABLE IF NOT EXISTS LOPHOC
(
	ID VARCHAR(10),
    NIENKHOA VARCHAR(20),
	TENLOP NVARCHAR(20) NOT NULL,
	GVCN VARCHAR(10) NOT NULL,
    SISOMAX INT NOT NULL,
    
	PRIMARY KEY(ID, NIENKHOA),
	FOREIGN KEY(GVCN) REFERENCES GIAOVIEN(ID)
);

CREATE TABLE IF NOT EXISTS HOCSINH
(
	ID VARCHAR(10),
    NIENKHOA VARCHAR(20),
	HOTEN NVARCHAR(50) NOT NULL,
    LOP VARCHAR(10),
    GIOITINH NVARCHAR(5),
    NGAYSINH DATE,
    DIACHI NVARCHAR(200),
    EMAIL VARCHAR(50),
    
	PRIMARY KEY(ID, NIENKHOA),
    FOREIGN KEY(LOP) REFERENCES LOPHOC(ID)
);


CREATE TABLE IF NOT EXISTS MONHOC
(
	ID VARCHAR(10),
	TENMH NVARCHAR(50),
    DIEMDAT FLOAT,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS DIEM
(
	IDHS VARCHAR(10),
    NIENKHOA VARCHAR(20),
    IDMH VARCHAR(10),
    HOCKI INT,
    DIEM15 FLOAT,
    DIEM45 FLOAT,
    DIEMHOCKI FLOAT,
    
    PRIMARY KEY(IDHS,IDMH, NIENKHOA, HOCKI),
    FOREIGN KEY(IDHS) REFERENCES HOCSINH(ID),
    FOREIGN KEY(IDMH) REFERENCES MONHOC(ID)
);